# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

right_format = """${custom.colima}$kubernetes"""

[character]
success_symbol = "[Œª](purple)"
error_symbol = "[Œª](red)"
vimcmd_symbol = "[‚ùÆ](green)"

[directory]
style = 'blue'

[git_branch]
format = "[$branch]($style)"
style = "fg:242"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)](cyan) "
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "‚â°"
ahead = '‚á°${count}'
diverged = '‚á°${ahead_count}‚á£${behind_count}'
behind = '‚á£${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[elixir]
disabled = false

[nodejs]
disabled = true

[battery]
disabled = true

[env_var.PROFILE]
variable = 'PROFILE'
format = 'with [\$PROFILE=$env_value](bold red) '
default = '(not set)'

[kubernetes]
disabled = false
symbol = '‚ò∏Ô∏è  '
format = '[$symbol$context( \($namespace\))]($style)'
style = 'bold dimmed fg:yellow'

[custom.colima]
command = "echo 'üê≥ colima'"
when = "test_colima.sh"
style = 'green'

[docker_context]
disabled = true

